repos:
  - repo: https://github.com/domluna/JuliaFormatter.jl
    rev: v2.1.6
    hooks:
      - id: julia-formatter
        files: \.jl$
        env:
          JULIA_PROJECT: .
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
