model:
  name: cs

params:
  β: 0.96
  σ: 2.0
  r: 0.02
  y: 1.0

grids:
  Na: 64
  a_min: 0.0
  a_max: 20.0

shocks:
  active: false

utility:
  u_type: CRRA

solver:
  method: "NN"
  epochs: 5
  batch: 64
  lr: 1.0e-3
  hid1: 64
  hid2: 64
  projection_kind: "softplus"
  stabilize: true
  stab_method: "log1p_square"
  residual_weighting: "none"
  weight_α: 5.0
  weight_κ: 20.0
  objective: euler_fb_aio
  v_h: 1.0

random:
  seed: 1234


