model:
  name: "BaselineConsumerSaving"

grids:
  a:
    min: 0.0
    max: 50.0
    N: 200

params:
  r: 0.02
  y: 1.0
  β: 0.96
  σ: 2.0

solver:
  method: "NN"
  epochs: 20
  batch: 64
  lr: 1e-3
  hid1: 64
  hid2: 64
  projection_kind: "softplus"
  stabilize: true
  stab_method: "log1p_square"
  residual_weighting: "none"
  weight_α: 5.0
  weight_κ: 20.0
  objective: euler_fb_aio
  v_h: 1.0
  w_min: 0.1
  w_max: 4.0

random:
  seed: 42
