model:
  name: "BaselineConsumerSaving"

params:
  β: 0.96
  σ: 2.0
  r: 0.02
  y: 1.0

grids:
  a:
    min: 0.0
    max: 20.0
    N: 64

shocks:
  active: true
  method: "rouwenhorst"
  ρ_shock: 0.9
  s_shock: 0.10
  Nz: 7
  validate: true

utility:
  u_type: "CRRA"

solver:
  method: "NN"
  epochs: 20
  batch: 64
  lr: 1.0e-3
  hid1: 64
  hid2: 64
  projection_kind: "softplus"
  stabilize: true
  stab_method: "log1p_square"
  residual_weighting: "none"
  weight_α: 5.0
  weight_κ: 20.0
  pretrain: false
  objective: euler_fb_aio
  v_h: 1.0
  w_min: 0.1
  w_max: 4.0

random:
  seed: 1234
