model:
  name: cs

params:
  β: 0.96
  σ: 2.0
  r: 0.02
  y: 1.0
  ρ_shock: 0.95
  σ_shock: 0.10

grids:
  Na: 200
  a_min: 0.0
  a_max: 20.0

shocks:
  active: false

utility:
  u_type: CRRA

solver:
  method: NN
  tol: 1.0e-6
  maxit: 10000
  verbose: true
  interp_kind: linear
  orders: [5]
  Nval: 50
  # NN training hyperparameters
  epochs: 200        # total epochs (pretrain uses half by default)
  batch: 128
  lr: 1.0e-4
  hidden: [64, 64]
  pretrain: true
  clip_norm: 1.0
  stabilize: true
  stab_method: log1p_square
  residual_weighting: none
  objective: euler_fb_aio
  v_h: 1.0
  w_min: 0.1
  w_max: 4.0

random:
  seed: 1234
