experiment:
  name: "simple_egm_smoke"
  seed: 1234

model:
  beta: 0.96
  sigma: 2.0
  r: 0.02
  y: 1.0
  a_min: 0.0
  a_max: 100.0

grid:
  Na: 100
  a_max: 100.0

solver:
  tol: 1.0e-6
  maxit: 10000
  verbose: true

shocks:
  active: true
  method: "rouwenhorst"   # or "tauchen"
  ρ_shock: 0.95
  σ_shock: 0.10
  Nz: 9
  m: 3.0                  # only used by Tauchen