experiment:
  name: "simple_egm_smoke"
  seed: 1234

model:
  beta: 0.96
  sigma: 2.0
  r: 0.02
  y: 1.0
  a_min: 0.0
  a_max: 20.0

grid:
  Na: 40
  a_max: 20.0

solver:
  tol: 1.0e-6
  maxit: 500
  verbose: true