model:
  name: cs

params:
  β: 0.96
  σ: 2.0
  r: 0.02
  y: 1.0

grids:
  Na: 50
  a_min: 0.0
  a_max: 20.0

utility:
  u_type: CRRA

solver:
  # run a single method name (string or symbol), a list of names, or use "all"
  method: all
  tol: 1.0e-6
  tol_pol: 1.0e-6
  maxit: 10000
  verbose: true
  interp_kind: linear
  orders: [5]
  Nval: 50
  # TimeIteration/EGM stability knobs
  relax: 0.5
  patience: 50
  warm_start: default
  # NN method options (used only when method includes NN)
  epochs: 200
  batch: 64
  lr: 1e-3
  objective: euler_fb_aio
  v_h: 0.5
  w_min: 0.1
  w_max: 4.0
  sigma_shocks: null

shocks:
  active: true
  method: "rouwenhorst"   # or "tauchen"
  ρ_shock: 0.95
  σ_shock: 0.10
  Nz: 7
  m: 3.0                  # only used with tauchen

random:
  seed: 1234

