model:
  name: cs

params:
  β: 0.96
  σ: 2.0
  r: 0.02
  y: 1.0
  ρ_shock: 0.95
  σ_shock: 0.10

grids:
  Na: 50
  a_min: 0.0
  a_max: 20.0

utility:
  u_type: CRRA

solver:
  method: EGM
  tol: 1.0e-6
  maxit: 10000
  verbose: true
  interp_kind: linear
  orders: [5]
  Nval: 50

random:
  seed: 1234
