name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1.11.6']
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
      - name: Instantiate
        run: julia -e 'using Pkg; Pkg.instantiate()'
      - name: Run tests
        run: julia -e 'using Pkg; Pkg.test("ThesisProject")'
      - name: Smoke (deterministic and stochastic)
        run: |
          julia scripts/smoke.jl

